name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: |
          python3 -m http.server 6006 --directory storybook-static --bind 0.0.0.0 &
          sleep 5
          npx loki test --requireReference --reactUri http://host.docker.internal:6006
      - name: upload loki artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: loki-results
          path: .loki
